### ISSUE TITLE
Reuse loop variable in for loop

### ISSUE THREAD

**Issue by lzl65825** [agiresearch/OpenP5#1]
In src/data/MultiTaskDataset.py, from line 223 to line 230:
```
for i in range(len(self.tasks)):
  if i == 0:
      start = 0
  else:
      start = self.task_index[i-1]
  end = self.task_index[i]
  task = self.tasks[i]
  self.task_data[task] = [i for i in range(start, end)]
```
the variable i is reused when constructing self.task_data[task].

**Comment by agiresearch** [comment]
The scope of the inner variable i is bounded by the array initialization [], and thus does not influence the value of the outer variable i. For example, you may try the following example code:
```
for i in range(0,10):
    array = [i for i in range(0,5)]
    print(array)
    print(i)
```

**Comment by lzl65825** [comment]
That makes sense. Thank you!
