### ISSUE TITLE
Typo in save_model code

### ISSUE THREAD

**Issue by lzl65825** [agiresearch/OpenP5#2]
In src/utils/utils.py, line 119 - 121:
``` 
def save_model(mode, path):
    torch.save(model.state_dict(), path)
    return
```
If my understanding is correct, the first parameter here should be "model" instead of "mode".

This function is called in src/runner/SingleRunner.py, line 158:
```
utils.save_model(self.model, self.args.model_path)
```

**Comment by shuyuan-x** [comment]
Thank you! This typo has been fixed.

**Comment by agiresearch** [comment]
fixed

**Comment by agiresearch** [comment]
fixed
