### ISSUE TITLE
ChildFailedError

### ISSUE THREAD

**Issue by doddodod** [agiresearch/OpenP5#21]
Hi, when I tried to run this repo following the readme file. The error of ChildFailedError raised as the picture shows. I want to conform whether it is a problem of my env?
![p5](https://github.com/agiresearch/OpenP5/assets/44559424/13cdeebc-b562-4eb2-951f-fd1d3b71f399)

**Comment by shuyuan-x** [comment]
Hi, This error is raised because some error interrupted the distributed learning. Is there any more detailed error message?

**Comment by octapha** [comment]
> Hi, when I tried to run this repo following the readme file. The error of ChildFailedError raised as the picture shows. I want to conform whether it is a problem of my env? ![p5](https://private-user-images.githubusercontent.com/44559424/295533768-13cdeebc-b562-4eb2-951f-fd1d3b71f399.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTc5MjIsIm5iZiI6MTcwODE5NzYyMiwicGF0aCI6Ii80NDU1OTQyNC8yOTU1MzM3NjgtMTNjZGVlYmMtYjU2Mi00ZWIyLTk1MWYtZmQxZDNiNzFmMzk5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxOTIwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjcwZWU4ZDYzZGMwNWVlMGJjMDdmZGE1ZDVkNDg4YjVlNDQwYjVjYzBmOTRiZDk0NWZhYWE3NDZmZTU5ZmNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h6pk-p_H_L2B4yGiAvtFDxRSEODCCdeQ3vYPc8cbo9k)

I encountered the same error because of insufficient storage space.
