### ISSUE TITLE
Is there any process code or link for my custom dataset can be applied by generate_dataset.py

### ISSUE THREAD

**Issue by darugareo** [agiresearch/OpenP5#22]
Thanks for publishing such a great repo.  I need to preprocess my custom data to a stage where generate_dataset.py can be applied, but I don't know how. is there any code or link ? Thank you

**Comment by shuyuan-x** [comment]
Hi, thanks for your interests in our project. The data processing code for MovieLens and Amazon is now available for your reference. You can locate the code within the /preprocessing folder.

**Comment by darugareo** [comment]
thank you very much!!!
