### ISSUE TITLE
Where is ./environment.txt

### ISSUE THREAD

**Issue by szdxcjh** [agiresearch/OpenP5#28]
Where is "./environment.txt"?

**Comment by shuyuan-x** [comment]
We have two implementations: one is based on Llama and fine-tuned using the Transformers Trainer, and the other is based on T5 and fine-tuned using our own implementation. We used different environments for each. The first environment can be found in './src/src_llama/environment_llama.txt', and the second one can be found in './src/src_t5/environment_t5.txt'.

**Comment by szdxcjh** [comment]
Thanks
