### ISSUE TITLE
Typo in SingleRunner.py

### ISSUE THREAD

**Issue by lzl65825** [agiresearch/OpenP5#3]
In src/runner/SingleRunner.py, line 153 and line 156,
```
153 valid_losses.append(valid_epoch_loss)
154 logging.info(f"The average valid loss for epoch {epoch+1} is {valid_epoch_loss}")
155 
156 if valid_epoch_loss == min(valid_losses):
```
The variable "valid_losses" is referred before being defined. I think it is a typo of "eval_losses" as "eval_losses" is defined in line 70 but not used in the function.

**Comment by shuyuan-x** [comment]
Thank you! The typo has been fixed.
