### ISSUE TITLE
Error when executing train.py file - pyarrow.lib.ArrowInvalid: cannot mix list and non-list, non-null values

### ISSUE THREAD

**Issue by igor17400** [agiresearch/OpenP5#5]
I've executed the scripts `generate_dataset.py` and `enerate_dataset_eval.py` for the `Electronics` and `Beauty` datasets. As a result, four files were generated. Two for each dataset, as shown below:

- `Beauty_sequential,straightforward_sequential_train.json`
- `Beauty_sequential,straightforward_sequential_validation_seen:0.json`
- `Electronics_sequential,straightforward_sequential_train.json`
- `Electronics_sequential,straightforward_sequential_validation_seen:0.json`

However, when I execute the `train.py` file the following error happens:

`pyarrow.lib.ArrowInvalid: cannot mix list and non-list, non-null values`

Does anyone knows what could be the cause of this error?

**Comment by igor17400** [comment]
Apparently if the lines:

```
TrainSet = train_data['train'].shuffle().map(process_func, batched=True)
ValidSet = valid_data['train'].shuffle().map(process_func, batched=True)
```
are switched to:

```
TrainSet = train_data['train'].shuffle().map(process_func) # without batched=True
ValidSet = valid_data['train'].shuffle().map(process_func)
```

it works. But don't know why 🧐

**Comment by shuyuan-x** [comment]
It appears that the current data format might lead to errors during batch preprocessing in some cases. We are actively addressing the issue and will provide a code update soon. For now, as you've discovered, setting 'batched' to 'False' serves as a workaround.

**Comment by igor17400** [comment]
Okay @shuyuan-x 
Thank you!
I'll try to explore what may be the problem and come back with feedback.
