### ISSUE TITLE
README: Missing files in non existing folders

### ISSUE THREAD

**Issue by breiteneder-felix** [agiresearch/OpenP5#8]
### Title
README: Missing files in non existing folders

### Description
I am currently trying to set up the project following the instructions provided in the README. However, I am having trouble understanding where the mentioned folders ./command folder. and ./test_command folder are stored. They are not in the repository and not in the provided download links for the checkpoints and data sets.

### Steps to Reproduce
1. Navigate to "Getting Started" in README.md
2. Follow the steps until Step "Usage" : The training command can be found in ./command folder.
4. The step mentions the file ML1M_random.sh in the folder ./command_folder, but it is not clear where this folder issupposed to be located.

1. Navigate to "Getting Started" in README.md
2. Follow the steps until Step "Checkpoint" : The training command can be found in ./command folder.
4. The step mentions the file ML1M_random.sh in the folder ./test_command, but it is not clear where this folder is supposed to be located.

### Expected Behavior
Clear instructions on where these folder are located. 

### Actual Behavior
Instructions are vague, and the mentioned folders are not present in the repository.

### Additional Context
I have checked both open and closed issues but couldn't find anything related to this problem.

Thank you in advance for your help!

**Comment by 1149722739** [comment]
the same question

**Comment by evison** [comment]
Dear @breiteneder-felix, thanks for your interest in the repo. The sample command files have been added into the repo. Hope they will be helpful to your work.
